-- vim.api.nvim_exec([[hi secondary_bg guibg=#101010 guifg=#FFFFFF
-- hi link NvimTreeNormal secondary_bg
-- hi link FloatTermDefaultTab secondary_bg
-- hi link FloatTermSelectTab cursor
-- hi link FloatBorder secondary_bg]],true)
