set('clipboard','unnamedplus')
set('completeopt','menuone,noselect')
set('t_Co','256')
set('number',true)
set('hidden',true)
set('ic',true)
set('tabstop',4)
set('encoding','UTF-8')
set('shiftwidth',2)
set('softtabstop',2)
set('scrolloff',2)
set('splitbelow',true)
set('splitright',true)
set('expandtab',true)
vim.g.mapleader = " "
