nsk('n', '<CR>', ':VimwikiFollowLink<CR>',buf_opts)
nsk('v', '<CR>', ':VimwikiFollowLink<CR>',buf_opts)
nsk('n', '<Tab><CR>', ':VimwikiGoBackLink<CR>',buf_opts)
nsk('n', '<Tab>=', ':VimwikiNormalizeLink<CR>',buf_opts)
nsk('v', '<Tab>=', ':VimwikiNormalizeLinkVisual<CR>',buf_opts)
nsk('n', '<Tab>x', 'o- [ ] ',buf_opts)
nsk('n', '<C-Space>', ':VimwikiToggleListItem<CR>',buf_opts)
nsk('n', '<Tab><Tab>', ':VimwikiNextLink<CR>',buf_opts)
nsk('n', '<S-Tab><S-Tab>',':VimwikiPrevLink<CR>',buf_opts)
